# Generated by Django 4.1.7 on 2023-02-19 08:23

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=1, upload_to=post.models.user_directory_path, verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
