# Generated by Django 4.1.7 on 2023-02-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
    ]
