# Generated by Django 4.1.7 on 2023-02-23 14:39

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='postpic',
            field=models.ImageField(default=1, upload_to=post.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostFileContent',
        ),
    ]
