# Generated by Django 4.1.7 on 2023-02-23 15:35

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_content_post_postpic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postpic',
            field=models.ImageField(upload_to=post.models.user_directory_path, verbose_name='Postpic'),
        ),
    ]
