# Generated by Django 4.1.7 on 2023-02-25 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models
import post.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_alter_post_postpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('videopic', models.FileField(upload_to=post.models.user_directory_path, validators=[post.validators.file_size], verbose_name='Videopic')),
                ('caption', models.TextField(max_length=1500, verbose_name='Caption')),
                ('vposted', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(related_name='vtags', to='post.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stream',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.video'),
        ),
    ]
