# Generated by Django 4.1.7 on 2023-02-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_vstream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='video',
        ),
    ]
