# Generated by Django 4.1.7 on 2023-02-25 09:01

from django.db import migrations, models
import post.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_stream_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videopic',
            field=models.FileField(upload_to='video/%y', validators=[post.validators.file_size]),
        ),
    ]
