# Generated by Django 4.1.7 on 2023-02-25 09:32

from django.db import migrations, models
import post.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_video_videopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videopic',
            field=models.FileField(default=1, upload_to='video/%y', validators=[post.validators.file_size]),
            preserve_default=False,
        ),
    ]
