# Generated by Django 4.1.5 on 2023-05-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_likes_created_likes_updated_likes_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='value',
        ),
    ]
