# Generated by Django 4.1.7 on 2023-02-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_field_profile_phone_profile_email_profile_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
