# Generated by Django 4.1.7 on 2023-02-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0006_field_profile_industry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='field_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
