# Generated by Django 4.1.7 on 2023-02-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0007_rename_last_name_profile_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
