# Generated by Django 4.1.7 on 2023-03-06 21:00

import authy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0008_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverpage',
            field=models.ImageField(blank=True, null=True, upload_to=authy.models.user_directory_path, verbose_name='coverpage'),
        ),
    ]
