# Generated by Django 4.1.7 on 2023-03-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0010_accounttype_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Choose_type',
            field=models.BooleanField(blank=True, max_length=150, null=True),
        ),
    ]
