# Generated by Django 4.1.7 on 2023-03-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0011_profile_choose_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Choose_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='Are_You_Business',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
