# Generated by Django 4.1.7 on 2023-03-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0012_remove_profile_choose_type_profile_are_you_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Are_You_Business',
            field=models.BooleanField(default=False),
        ),
    ]
