# Generated by Django 4.1.7 on 2023-03-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0013_alter_profile_are_you_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Account_Type',
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
    ]
