# Generated by Django 4.1.7 on 2023-03-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0016_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
