# Generated by Django 4.1.7 on 2023-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0019_remove_friend_profile_remove_profile_friends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
