# Generated by Django 4.1.7 on 2023-07-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0020_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Are_You_Business',
            new_name='blue_checker',
        ),
        migrations.AddField(
            model_name='profile',
            name='golden_checker',
            field=models.BooleanField(default=False),
        ),
    ]
