# Generated by Django 4.1.7 on 2023-07-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0021_rename_are_you_business_profile_blue_checker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_checker',
            field=models.BooleanField(default=False),
        ),
    ]
